default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  password:

development:
  <<: *default
  database: dc_development

test:
  <<: *default
  database: dc_test

production:
  <<: *default
  database: dc_production
